namespace MineWorldData
{
    public class Constants
    {
        public const int LindgrenVersion = 285;
        public const int EasyconfigVersion = 61482;
        public const int MineworldclientVersion = 0;
        public const int MineworldserverVersion = 0;
        public const int MineworlddataVersion = 0;
        public const int MineworldPort = 5565;
    }

    public enum PacketType
    {
        PlayerLeft,
        PlayerJoined,
        WorldMapSize,
        PlayerInWorld,
        PlayerBlockSet,
        PlayerBlockUse,
        PlayerInitialUpdate,
        PlayerMovementUpdate,
        PlayerNameSet,
    }

    //For more info check http://www.minecraftwiki.net/wiki/Data_values#Block_IDs_.28Minecraft_Official_Release.29
    public enum BlockTypes
    {
        Air = 0,
        Stone = 1,
        Grass = 2,
        Dirt = 3,
        Cobblestone = 4,
        Woodenplanks = 5,
        Saplings = 6,
        Bedrock = 7,
        Water = 8,
        Water2 = 9,
        Lava = 10,
        Lava2 = 11,
        Sand = 12,
        Gravel = 13,
        Goldore = 14,
        Ironore = 15,
        Coalore = 16,
        Wood = 17,
        Leaves = 18,
        Sponge = 19,
        Glass = 20,
        Lapisore = 21,
        Lapisblock = 22,
        Dispenser = 23,
        Sandstone = 24,
        Noteblock = 25,
        Bed = 26,
        Powererdrail = 27,
        Detectorrail = 28,
        Stickypiston = 29,
        Cobweb = 30,
        Tallgrass = 31,
        Deadbush = 32,
        Piston = 33,
        Pistonextension = 34,
        Wool = 35,
        Unused1 = 36, //Block moved by piston
        Floweryellow = 37,
        Flowerred = 38,
        Brownmushroom = 39,
        Redmushroom = 40,
        Blockofgold = 41,
        Blockofiron = 42,
        Doubleslabs = 43,
        Slabs = 44,
        Bricks = 45,
        Tnt = 46,
        Bookshelf = 47,
        Mossstone = 48,
        Obsidian = 49,
        Torch = 50,
        Fire = 51,
        Monsterspawner = 52,
        Woodenstairs = 53,
        Chest = 54,
        Redstonewire = 55,
        Diamondore = 56,
        Blockofdiamond = 57,
        Craftingtable = 58,
        Wheatseeds = 59,
        Farmland = 60,
        Furnace = 61,
        Burningfurnace = 62,
        Signpost = 63,
        Woodendoor = 64,
        Ladders = 65,
        Rails = 66,
        Cobbelstonestairs = 67,
        Wallsign = 68,
        Lever = 69,
        Stonepressureplate = 70,
        Irondoor = 71,
        Woodenpressureplate = 72,
        Redstoneore = 73,
        Glowingredstoneore = 74,
        Redstonetorchoff = 75,
        Redstonetochon = 76,
        Stonebutton = 77,
        Snow = 78,
        Ice = 79,
        Snowblock = 80,
        Cactus = 81,
        Clayblock = 82,
        Sugarcane = 83,
        Jukebox = 84,
        Fence = 85,
        Pumpkin = 86,
        Netherrack = 87,
        Soulsand = 88,
        Glowstone = 89,
        Portal = 90,
        Jackolatern = 91,
        Cake = 92,
        Redstonerepeateroff = 93,
        Redstonerepeateron = 94,
        Lockedchest = 95,
        Trapdoor = 96,
        Hiddensilverfish = 97,
        Stonebricks = 98,
        Hugebrownmushroom = 99,
        Hugeredmushroom = 100,
        Ironbars = 101,
        Glasspane = 102,
        Melon = 103,
        Pumpkinstem = 104,
        Melonstem = 105,
        Vines = 106,
        Fencegate = 107,
        Brickstairs = 108,
        Stonebrickstairs = 109,
        Mycelium = 110,
        Lilypad = 111,
        Netherbrick = 112,
        Netherbrickfence = 113,
        Netherbrickstairs = 114,
        Netherwart = 115,
        Enchantmenttable = 116,
        Brewingstand = 117,
        Cauldron = 118,
        Endportal = 119,
        Endportalframe = 120,
        Endstone = 121,
        Dragonegg = 122,
        Redstonelampoff = 123,
        Redstonelampon = 124,
        //Max defined by minecraft
        Max = 125,
    }
}